package com.aviansh.aifilemanager.domain.agent

import android.util.Log
import com.aviansh.aifilemanager.domain.ai.LLMGenerationResponse
import com.aviansh.aifilemanager.domain.ai.LLMProvider
import com.aviansh.aifilemanager.domain.data.ChatLmMessage
import com.aviansh.aifilemanager.domain.data.ChatLmRole
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject

/**
 * Outcome of a single agent turn.
 */
sealed class AgentOutcome {
    /** The agent finished and produced an answer. */
    data class Answer(val text: String) : AgentOutcome()

    /** The agent needs the user to approve a destructive tool call before continuing. */
    data class NeedsConfirmation(val action: PendingAction) : AgentOutcome()

    data class Failed(val error: String) : AgentOutcome()
}

/**
 * Agentic executor.
 *
 * Instead of asking the model to emit a batch "plan" that is generated by Python and committed
 * transactionally, the model drives a ReAct loop: it calls real tools one at a time, sees each
 * result, and decides what to do next. Mutations happen immediately through the tools, with
 * destructive ones gated behind user confirmation and recoverable via the trash.
 *
 * The loop is resumable: when a destructive call needs approval the engine returns
 * [AgentOutcome.NeedsConfirmation] along with the conversation so far, and [resume] continues
 * from exactly that point once the user decides.
 */
class AgentEngine(
    private val llmProvider: LLMProvider,
    private val toolRegistry: ToolRegistry,
    private val maxSteps: Int = 16,
    private val maxConsecutiveFailures: Int = 3
) {

    private val tag = "AgentEngine"

    /**
     * Mutable transcript for the current turn. Exposed so the ViewModel can hand it back to
     * [resume] after a confirmation round-trip.
     */
    class Session(
        val userPrompt: String,
        internal val transcript: MutableList<ChatLmMessage>,
        internal var stepsUsed: Int = 0,
        internal var consecutiveFailures: Int = 0,
        internal var pending: PendingAction? = null
    )

    fun systemPrompt(currentDirectory: String): String = """
You are a file management agent running on an Android device. You act directly on the user's
files by calling tools, one at a time, and you see the result of each call before deciding the
next step.

The user is currently browsing: $currentDirectory
Shared storage root: /storage/emulated/0

TOOLS
${toolRegistry.describeTools()}

HOW TO RESPOND
Respond with exactly one JSON object and nothing else. Either call a tool:
{"thought": "one short sentence on why", "tool": "tool_name", "args": {"path": "/storage/emulated/0/..."}}

Or finish the turn with your answer to the user:
{"thought": "why you are done", "answer": "what you did or found, in plain language"}

RULES
- Explore before acting: use list_directory / search_files / file_info to confirm what exists.
- Use absolute paths. Relative paths will be rejected.
- Act on one thing at a time. Do not try to batch many operations into a single call.
- Tools marked REQUIRES USER CONFIRMATION pause for the user's approval. That is normal —
  just request the call, and you will be told whether it was approved.
- If the user declines a call, respect it. Do not retry the same call; either take a different
  approach or finish and explain.
- Deletes are recoverable from the app trash, but still treat them seriously.
- If a call fails, read the error and adapt. Never repeat an identical failing call.
- When the task is done, or if it cannot be done, reply with "answer". Always end the turn with
  an answer rather than looping.
- Be concise. The user sees each step already; the answer should summarise, not restate.
""".trimIndent()

    suspend fun start(
        userPrompt: String,
        currentDirectory: String,
        history: List<ChatLmMessage>,
        onEvent: suspend (TimelineEvent) -> Unit = {}
    ): Pair<Session, AgentOutcome> = withContext(Dispatchers.IO) {
        val transcript = history.toMutableList()
        transcript.add(ChatLmMessage(ChatLmRole.USER, userPrompt))
        val session = Session(userPrompt, transcript)
        session to runLoop(session, currentDirectory, onEvent)
    }

    /**
     * Continues a turn after the user approved or declined the pending destructive call.
     */
    suspend fun resume(
        session: Session,
        currentDirectory: String,
        approved: Boolean,
        onEvent: suspend (TimelineEvent) -> Unit = {}
    ): AgentOutcome = withContext(Dispatchers.IO) {
        val pending = session.pending
            ?: return@withContext AgentOutcome.Failed("No action was awaiting confirmation.")
        session.pending = null

        if (!approved) {
            onEvent(TimelineEvent.SystemMessage("You declined: ${pending.preview}"))
            session.transcript.add(
                ChatLmMessage(
                    ChatLmRole.USER,
                    "[SYSTEM] The user DECLINED the call ${pending.toolName}(${pending.args}). " +
                        "Do not attempt it again. Either continue differently or finish with an answer."
                )
            )
            return@withContext runLoop(session, currentDirectory, onEvent)
        }

        val tool = toolRegistry.find(pending.toolName)
            ?: return@withContext AgentOutcome.Failed("Unknown tool ${pending.toolName}")

        onEvent(TimelineEvent.AgentThought("Approved — ${pending.preview}"))
        applyToolResult(session, tool, pending, onEvent)
        runLoop(session, currentDirectory, onEvent)
    }

    private suspend fun runLoop(
        session: Session,
        currentDirectory: String,
        onEvent: suspend (TimelineEvent) -> Unit
    ): AgentOutcome {
        val system = systemPrompt(currentDirectory)

        while (session.stepsUsed < maxSteps) {
            session.stepsUsed++
            val isLastStep = session.stepsUsed == maxSteps

            if (isLastStep) {
                session.transcript.add(
                    ChatLmMessage(
                        ChatLmRole.USER,
                        "[SYSTEM] Step budget reached. Reply now with an \"answer\" summarising " +
                            "what you did and anything left undone. Do not call another tool."
                    )
                )
            }

            val response = llmProvider.generate(
                prompt = session.transcript.last().content,
                systemPrompt = system,
                conversation = session.transcript.dropLast(1)
            )

            val raw = when (response) {
                is LLMGenerationResponse.SUCCESS -> response.message
                is LLMGenerationResponse.FAILURE -> return AgentOutcome.Failed(response.error)
            }

            val decision = parseDecision(raw)
            if (decision == null) {
                Log.w(tag, "Unparsable model response: ${raw.take(200)}")
                session.transcript.add(ChatLmMessage(ChatLmRole.ASSISTANT, raw))
                session.transcript.add(
                    ChatLmMessage(
                        ChatLmRole.USER,
                        "[SYSTEM] That was not valid JSON. Reply with exactly one JSON object " +
                            "containing either \"tool\" and \"args\", or \"answer\"."
                    )
                )
                continue
            }

            session.transcript.add(ChatLmMessage(ChatLmRole.ASSISTANT, decision.raw))

            decision.answer?.let { answer ->
                onEvent(TimelineEvent.AgentAnswer(answer))
                return AgentOutcome.Answer(answer)
            }

            val toolName = decision.tool ?: continue
            val tool = toolRegistry.find(toolName)
            if (tool == null) {
                onEvent(TimelineEvent.ToolCall(toolName, toolName, error = "Unknown tool"))
                session.transcript.add(
                    ChatLmMessage(
                        ChatLmRole.USER,
                        "[SYSTEM] There is no tool called '$toolName'. Available: " +
                            toolRegistry.all().joinToString { it.name }
                    )
                )
                continue
            }

            decision.thought?.takeIf { it.isNotBlank() }?.let { onEvent(TimelineEvent.AgentThought(it)) }

            val preview = tool.previewFor(decision.args)
            val action = PendingAction(tool.name, decision.args, preview)

            if (tool.spec.destructive) {
                session.pending = action
                onEvent(TimelineEvent.ConfirmationRequest(action))
                return AgentOutcome.NeedsConfirmation(action)
            }

            applyToolResult(session, tool, action, onEvent)

            if (session.consecutiveFailures >= maxConsecutiveFailures) {
                session.transcript.add(
                    ChatLmMessage(
                        ChatLmRole.USER,
                        "[SYSTEM] ${session.consecutiveFailures} calls failed in a row. Stop retrying " +
                            "this approach. Either do something different or finish with an answer " +
                            "explaining the blocker."
                    )
                )
                session.consecutiveFailures = 0
            }
        }

        return AgentOutcome.Failed(
            "The agent used all $maxSteps steps without finishing. Try a more specific request."
        )
    }

    private suspend fun applyToolResult(
        session: Session,
        tool: AgentTool,
        action: PendingAction,
        onEvent: suspend (TimelineEvent) -> Unit
    ) {
        onEvent(TimelineEvent.ToolCall(tool.name, action.preview))

        val result = try {
            tool.execute(action.args)
        } catch (e: kotlinx.coroutines.CancellationException) {
            throw e
        } catch (e: Exception) {
            ToolResult.Failure(e.message ?: e::class.java.simpleName)
        }

        when (result) {
            is ToolResult.Success -> {
                session.consecutiveFailures = 0
                onEvent(TimelineEvent.ToolCall(tool.name, action.preview, result = result.summary))
                session.transcript.add(
                    ChatLmMessage(ChatLmRole.USER, "[TOOL ${tool.name} OK]\n${result.output}")
                )
            }

            is ToolResult.Failure -> {
                session.consecutiveFailures++
                onEvent(TimelineEvent.ToolCall(tool.name, action.preview, error = result.error))
                session.transcript.add(
                    ChatLmMessage(ChatLmRole.USER, "[TOOL ${tool.name} FAILED]\n${result.error}")
                )
            }
        }
    }

    internal data class Decision(
        val raw: String,
        val thought: String?,
        val tool: String?,
        val args: JSONObject,
        val answer: String?
    )

    /**
     * Extracts the decision JSON from a model response, tolerating markdown fences and
     * surrounding prose.
     */
    internal fun parseDecision(rawText: String): Decision? {
        val json = extractJsonObject(rawText) ?: return null
        val obj = try {
            JSONObject(json)
        } catch (_: Exception) {
            return null
        }

        val answer = obj.optString("answer").takeIf { it.isNotBlank() && !obj.isNull("answer") }
        val tool = obj.optString("tool").takeIf { it.isNotBlank() && !obj.isNull("tool") }
        if (answer == null && tool == null) return null

        // Tolerate args arriving as a JSON string instead of an object.
        val args = when (val a = obj.opt("args")) {
            is JSONObject -> a
            is String -> try {
                JSONObject(a)
            } catch (_: Exception) {
                JSONObject()
            }
            else -> JSONObject()
        }

        return Decision(
            raw = json,
            thought = obj.optString("thought").takeIf { it.isNotBlank() },
            tool = tool,
            args = args,
            answer = answer
        )
    }

    /** Finds the first balanced {...} block, ignoring braces inside strings. */
    internal fun extractJsonObject(text: String): String? {
        val cleaned = text.trim().removePrefix("```json").removePrefix("```").removeSuffix("```").trim()
        val start = cleaned.indexOf('{')
        if (start < 0) return null

        var depth = 0
        var inString = false
        var escaped = false

        for (i in start until cleaned.length) {
            val c = cleaned[i]
            when {
                escaped -> escaped = false
                c == '\\' && inString -> escaped = true
                c == '"' -> inString = !inString
                !inString && c == '{' -> depth++
                !inString && c == '}' -> {
                    depth--
                    if (depth == 0) return cleaned.substring(start, i + 1)
                }
            }
        }
        return null
    }
}
